[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 100
'''
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_source = '''
  let g:deoplete#sources#jedi#server_timeout = 20
'''
on_ft = 'python'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap <Space>up :DeniteBufferDir file_rec -mode=normal<CR>
  nnoremap <Space>uh :Denite file_mru -mode=normal<CR>
  nnoremap <Space>ub :Denite buffer -mode=normal<CR>
  nnoremap <Space>uwg :DeniteCursorWord grep -mode=normal<CR>
  nnoremap <Space>ur :Denite -resume -mode=normal<CR>
'''
hook_post_source = '''
"  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
"  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>',
"  'noremap')

  " jj で denite/insert を抜けるようにする
  call denite#custom#map('insert', '<C-j>', '<denite:enter_mode:normal>', 'noremap')
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <Space>h :NERDTreeToggle<CR>
nnoremap <Space>e :NERDTreeToggle %:h<CR>
"nnoremap <Space>e :NERDTreeToggle<CR>
'''
on_source = ['nerdtree-yank-mapping', 'nerdtree-execute']


