#report system
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
" for clear plugins
" call map(dein#check_clean(), "delete(v:val, 'rf')")
'''
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': 200,
    \ 'wincol': 50,
    \ 'highlight_matched_char': 'QuickFixLine',
    \ 'highlight_matched_range': 'Visual',
    \ 'highlight_window_background': 'Visual',
    \ 'highlight_filter_background': 'DiffAdd',
    \ 'winrow': 1,
    \ })

  nnoremap <Space>uf :DeniteProjectDir file/rec -highlight-filter-background=Search <CR>

  nnoremap <Space>uh :Denite file/old <CR>
  nnoremap <Space>ul :Denite line<CR>
  nnoremap <Space>ub :Denite buffer <CR>
  nnoremap <Space>u[  :DeniteCursorWord grep <CR>
  nnoremap <Space>ug  :Denite grep <CR>
  nnoremap <Space>ur :Denite -resume <CR>
  " Define mappings
  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
  endfunction

  autocmd FileType denite-filter call s:denite_filter_my_settings()
  function! s:denite_filter_my_settings() abort
imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)
  endfunction

  if executable('rg')
  call denite#custom#var('file_rec', 'command',
      \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
  endif
  '''
  hook_post_source = '''
"  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
"  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>',
"  'noremap')
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = '''
let g:echodoc_enable_at_startup = 1
let g:echodoc#type = "virtual"
'''
[[plugins]]
repo ='itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
        \ 'separator': { 'left': '', 'right': '' },
        \ 'subseparator': { 'left': '', 'right': '' },
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \ 'left': [['mode', 'paste'],
        \          ['gitbranch', 'gitstatus', 'readonly', 'filename', 'modified']],
        \  'right': [['linter_errors', 'linter_warnings', 'linter_ok'], ['lineinfo'], ['fileformat', 'fileencoding'], ['filetype']]
        \ },
        \ 'inactive': {
        \ 'left': [['gitbranch', 'gitstatus', 'filename', 'modified']],
        \  'right': [['linter_errors', 'linter_warnings', 'linter_ok'], ['lineinfo'], ['fileformat', 'fileencoding'], ['filetype']]
        \ },
        \ 'component_expand': {
        \   'gitbranch': 'GitBranch',
        \   'gitstatus': 'GitStatus',
        \   'filename': 'MyFilename',
        \   'filetype': 'FileType',
        \ },
        \ 'component_type': {
        \   'readonly': 'error',
        \   'linter_warnings': 'warning',
        \   'linter_errors': 'error',
        \   'linter_ok': 'ok'
        \ },
        \ }

  function! MyFilename()
    return winwidth(0) > 160 ?
          \ expand('%:p') !=# '' ? expand('%:p') : '[No Name]' :
          \ winwidth(0) > 120 ? 
          \ expand('%:t') !=# '' ? expand('%:h') .'/'. expand('%:t') : '[No Name]' :
          \ expand('%:t') !=# '' ? expand('%:h') .'/'. expand('%:t') : '[No Name]'
  endfunction

  function GitBranch()
    let branch = gina#component#repo#branch()
    return branch == '' ? '' : printf('%s%s', ' ', branch)
  endfunction

  function! FileType()
    return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
  endfunction

  function! GitStatus()
    let staged = gina#component#status#staged()
    let unstaged = gina#component#status#unstaged()
    let conflicted = gina#component#status#conflicted()
    return windwidth(0) > 120 ? printf(
          \ 's:%s u:%s c:%s',
          \ staged,
          \ unstaged,
          \ conflicted,
          \) : ''
    let result = system('git --git-dir=' . fugitive#extract_git_dir(expand('%:p')) . ' --work-tree=' . substitute(fugitive#extract_git_dir(expand('%:p')), '.git', '', 'g') .' status')
    " let dir = a:0 ? a:1 : (exists('b:git_dir') && b:git_dir !=# '' ? b:git_dir : fugitive#extract_git_dir(expand('%:p')))

    let status = ''
    if stridx(result, 'up-to-date') != -1
      :let status = status . ''
    endif
    if stridx(result, 'rebase in progress') != -1
      :let status = status . '!conflict|'
    endif
    if stridx(result, 'Changes to be committed') != -1
      :let status = status . '+'
    endif
    if stridx(result, 'Changes not staged for commit') != -1
      :let status = status . '-'
    endif
    if stridx(result, 'Untracked') != -1
      :let status = status . '?'
    endif
    return status
  endfunction
'''
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''

[[plugins]] # terminal
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
  nnoremap <silent> ,rc :TREPLSendFile<cr>
  nnoremap <silent> ,rl :TREPLSendLine<cr>
  vnoremap <silent> ,rl :TREPLSendSelection<cr>
  nnoremap <Space>vp :vert botright T cd %:h; clear;<CR>
  nnoremap <Space>r :vert botright T cd %:h; clear; ipython --no-autoindent <CR>
  nnoremap <Space>vw :T cd ~/Documents/Workspace/<CR>
  nnoremap <Space>vv :Ttoggle<CR>
  nnoremap <Space>vo :vert botright Topen<CR> cd %:h; clear;<CR>
  nnoremap <Space>vc :Tclose<CR>
  let g:neoterm_autoinsert = 1
  " let g:neoterm_open_in_all_tabs = 1
  let g:neoterm_repl_php = 'php'
'''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
  " source ~/.config/nvim/plugins/neoterm.rc.vim
'''
[[plugins]]
repo = 'Shougo/vimproc.vim'
# if = "!has('nvim')"
build = 'make'

[[plugins]]
repo ='w0rp/ale'
hook_add = '''
nmap <silent> <C-e><C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-e><C-k> <Plug>(ale_previous_wrap)

" let g:ale_set_loclist = 0
" let g:ale_set_quickfix = 1

let g:ale_fixers = {
  \    'javascript': ['eslint'],
  \    'typescript': ['eslint'],
  \    'vue': ['eslint'],
  \    'css': ['stylelint'],
  \    'scss': ['stylelint'],
  \}
let g:ale_fix_on_save = 1

let g:ale_sign_error = ''
let g:ale_sign_warning = ''
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_completion_enabled = 0

let g:ale_linters = {
\ 'cs': ['OmniSharp']
\}
let g:ale_cs_mcsc_assemblies = ['/Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Managed/UnityEngine.dll']
let g:ale_cs_csc_assemblies = ['/Applications/Unity/Hub/Editor/2019.2.9f1/Unity.app/Contents/Managed/UnityEngine.dll']
let g:ale_cs_mcsc_assemblies += [expand('%:h') . '/obj/Debug']
let g:ale_cs_csc_assemblies += [expand('%:h') . '/obj/Debug']
'''
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_leader_key=";"
  let g:EasyMotion_smartcase=1
  map f <Plug>(easymotion-fl)
  map t <Plug>(easymotion-tl)
  map F <Plug>(easymotion-Fl)
  map T <Plug>(easymotion-Tl)

  nmap s <Plug>(easymotion-s)
  xmap s <Plug>(easymotion-s)
  omap s <Plug>(easymotion-t)

  nmap g/ <Plug>(easymotion-sn)
  xmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)

  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1

  let g:EasyMotion_use_upper = 1
'''
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''
[[plugins]]
repo = 'michaeljsmith/vim-indent-object'


[[plugins]]
repo = 'itmammoth/doorboy.vim'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
'''

# Filetype
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Typescript
 [[plugins]]
 repo = 'HerringtonDarkholme/yats.vim'

# UI
[[plugins]]
repo = 'RRethy/vim-illuminate'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''
[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  if !has('mac')
    let g:solarized_termcolors=256
  endif
  au MyAutoCmd VimEnter * nested colorscheme solarized
  set background=light
'''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'jreybert/vimagit'
[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  nnoremap <Space>gb :Gina blame --opener=vsplit<CR>
  nnoremap <Space>gs :Gina status --opener=vsplit<CR>
  nnoremap <Space>gd :Gina diff --opener=vsplit<CR>
  nnoremap <Space>gl :Gina log --opener=vsplit<CR>
  nnoremap <Space>glc :Gina log : --opener=vsplit<CR>
'''
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'cohama/agit.vim'

# Utility
[[plugins]]
repo = 'hiradd/easydiary'
hook_add = '''
  let g:easydiary_directory = '~/Workspace/note/'
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
  nnoremap <Space>tm :TableModeToggle<CR>
'''

[[plugins]]
repo = 'janko/vim-test'
hook_add = '''
nmap <silent> t<C-n> :TestNearest<CR>
'''

# 2020
# [[plugins]]
# repo = 'preservim/nerdcommenter'
# hook_add ='''
#   map <C-c><C-u> <plug>NERDCommenterUncomment
#   map <C-c><C-s> <plug>NERDCommenterSexy
#   map <C-c><C-c> <plug>NERDCommenterAlignLeft
#   let NERDSpaceDelims=1
# '''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add ='''
nmap <silent> <C-c><C-c> :TComment<CR>
vmap <silent> <C-c><C-c> :TComment<CR>

'''

[[plugins]]
repo = 'rhysd/git-messenger.vim'
hook_add = '''
  nnoremap <Space>gm :GitMessenger<CR>
'''

[[plugins]]
repo = 'ElmCast/elm-vim'
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  nmap <silent> <space>cd <Plug>(coc-definition)
  nmap <silent> <space>cy <Plug>(coc-type-definition)
  nmap <silent> <space>ci <Plug>(coc-implementation)
  nmap <silent> <space>cr <Plug>(coc-references)
  nmap <silent> <space>crn <Plug>(coc-rename)
  nmap <silent> <space>qf <Plug>(coc-fix-current)
  nmap <silent> <space>qa <Plug>(coc-codeaction)

  nnoremap <silent> K :call <SID>show_documentation()<CR>

  function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
  endfunction

  nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
  nnoremap <silent><nowait> gs  :<C-u>CocList -I symbols<cr>


imap <C-l> <Plug>(coc-snippets-expand)
vmap <C-h> <Plug>(coc-snippets-select)
let g:coc_snippet_next = '<c-k>'
let g:coc_snippet_prev = '<c-g>'
imap <C-g> <Plug>(coc-snippets-expand-jump)
xmap <Space>x  <Plug>(coc-convert-snippet)
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo='lambdalisue/fern.vim'
hook_add = '''
nnoremap <space>e :Fern . -reveal=%:p -drawer -toggle<CR>
nnoremap <space><C-e> :Fern %:h -drawer -toggle<CR>
function! s:init_fern() abort
  " Use 'select' instead of 'edit' for default 'open' action
  nmap <buffer> T <Plug>(fern-action-open:edit)
  nnoremap <buffer> t <Nop>
  nmap <buffer> r <Plug>(fern-action-reload)

endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
'''

[[plugins]]
repo ='tyru/capture.vim'

[[plugins]]
repo ='mattn/webapi-vim'

[[plugins]]
repo ='liuchengxu/vista.vim'
hook_add = '''
let g:vista_icon_indent = [">", ">>"]
let g:vista_default_executive = 'coc'
let g:vista_fzf_preview = ['right:50%']
let g:vista_sidebar_width = 50
let g:vista#renderer#icons = {
\   "function": "\ue60b",
\   "variable": "v",
\   "method": "\ue60b",
\   "property": "v",
\  }

nnoremap <space>vl :Vista show<CR>
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'chemzqm/denite-git'
